name: Build Spilo

on:
  workflow_call:
    inputs:
      production:
        required: true
        type: boolean
        default: false
      spilo_repo:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      production:
        required: true
        type: boolean
        default: false
      spilo_repo:
        required: true
        type: string
        default: 011789831835.dkr.ecr.us-east-1.amazonaws.com/spilo

jobs:
  push_spilo:
    if: github.repository == 'hydrasdb/hydra-internal'
    name: Push Spilo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        platforms: linux/amd64
        driver-opts: network=host
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1
        mask-aws-account-id: no
    - name: Login to Amazon ECR
      id: spilo-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: "011789831835"
    - name: Bake and push spilo
      uses: docker/bake-action@v2.3.0
      with:
        push: true
        targets: spilo
        set: |
          *.cache-from=type=gha
          *.platform=linux/amd64
          spilo.tags=${{ inputs.spilo_repo }}:${{ inputs.production && github.sha || format('dev-{0}-{1}', github.ref, github.sha) }}
          ${{ inputs.production && format('spilo.tags={0}:latest', inputs.spilo_repo) || '' }}
